import test from "node:test";
import assert from "node:assert/strict";
import { buildCanonicalEvidenceRoute } from "@/lib/canonical-evidence-router";
import { buildFitGapProjection } from "@/lib/fit-gap-reasoning";
import { buildFitGapConsumerProjection } from "@/lib/fit-gap-consumer";
import { buildDemonstrationObjectiveConsumerProjection } from "@/lib/demonstration-objective-consumer";
import { buildCanonicalStrategyBridgeProjection } from "@/lib/canonical-strategy-bridge";
import { buildCanonicalProbeRoutingProjection } from "@/lib/canonical-probe-router";
import { buildCanonicalFeedbackMirrorUpdate, validateCanonicalFeedbackMirrorUpdate } from "@/lib/canonical-feedback-mirror";
import { buildCanonicalReasoningProjection } from "@/lib/canonical-reasoning-adapter";
import type { EvidenceLedger } from "@/lib/canonical-evidence-model";
const span=(id:string,document_id:string,text:string)=>({id,document_id,text,start_offset:0,end_offset:text.length,language:"en"});
const atom=(id:string,source_span_id:string,action:string,object:string)=>({id,source_span_id,provenance:{source_type:"CV" as const,language:"en",extraction_method:"LLM" as const},subject:{actor:"candidate",ownership:"INDIVIDUAL" as const},action:{normalized_action:action,object},context:{},scale:{},time:{},outcome:null,assertion:{type:"RESPONSIBILITY" as const,polarity:"AFFIRMATIVE" as const},verifiability:{has_quantifiable_metric:false,has_third_party_entity:false,has_time_anchor:false},extraction_confidence:1});
function ledger():EvidenceLedger{return {source_spans:[span("CV","CV","Managed finance."),span("JD","JD","Mining operations experience."),span("I1","INTERVIEW","I managed the reporting cycle.")],evidence:[atom("A","CV","managed","finance")],requirements:[{id:"R",source_span_id:"JD",normalized_requirement:"Mining operations experience",category:"RESPONSIBILITY",salience:"CORE",facets:[{id:"F",type:"CONTEXT",requirement:"Mining operations experience",source_span_id:"JD"}],extraction_confidence:1}],support_judgments:[{id:"S",requirement_id:"R",facet_id:"F",status:"CONTRADICTORY",supporting_evidence_ids:["A"],rationale:"No mining experience documented.",confidence:1,abstained:false,support_basis:"DOCUMENTED"}],requirement_statuses:[{requirement_id:"R",status:"CONTRADICTED"}],unresolved_items:[{id:"U",requirement_id:"R",facet_ids:["F"],type:"CONFLICTING",supporting_evidence_ids:[],contradiction_evidence_ids:["A"],absence_basis:"EXPLICIT_CONTRADICTION",negation_evidence_ids:[]}],candidate_elicitations:[],demonstration_objectives:[{id:"O",target_unresolved_item_id:"U",observable_cue:"State the boundary honestly.",supporting_true_atom_ids:[],truthfulness_boundary:{permitted_claims:["State source facts."],prohibited_claims:["Do not claim mining experience."]},candidate_gap_classification:"EXPERIENCE_GAP",probe_family:"CONTEXT"}]};}
test("D8 accepts explicitly grounded interview evidence",()=>{const l=ledger();const x=full(l);const e={...atom("I-A","I1","managed","reporting cycle"),provenance:{source_type:"CANDIDATE_ELICITED" as const,language:"en",extraction_method:"LLM" as const},assertion:{type:"ELICITED" as const,polarity:"AFFIRMATIVE" as const}};const u=buildCanonicalFeedbackMirrorUpdate(x.d7,x.d6,x.d4,x.d2,x.d3,x.d5,l,[{observation_id:"O1",requirement_id:"R",source_span:l.source_spans[2]!,evidence:e,claim_boundary:"CANDIDATE_STATED"}]);assert.equal(u.observations.length,1);});
test("D8 rejects non-interview provenance",()=>{const l=ledger();const x=full(l);const e=atom("I-A","I1","managed","reporting cycle");const p={version:"d8-v1" as const,observations:[{observation_id:"O1",requirement_id:"R",source_span:l.source_spans[2]!,evidence:e,claim_boundary:"CANDIDATE_STATED" as const}]};const v=validateCanonicalFeedbackMirrorUpdate(p,x.d7,x.d6,x.d4,x.d2,x.d3,x.d5,l);assert.equal(v.valid,false);assert.match(v.errors.join(" | "),/candidate-elicited provenance/i);});
test("D8 rejects negated updates",()=>{const l=ledger();const x=full(l);const e={...atom("I-A","I1","did not","reporting cycle"),assertion:{type:"ELICITED" as const,polarity:"NEGATED" as const},provenance:{source_type:"CANDIDATE_ELICITED" as const,language:"en",extraction_method:"LLM" as const}};const p={version:"d8-v1" as const,observations:[{observation_id:"O1",requirement_id:"R",source_span:l.source_spans[2]!,evidence:e,claim_boundary:"CANDIDATE_STATED" as const}]};const v=validateCanonicalFeedbackMirrorUpdate(p,x.d7,x.d6,x.d4,x.d2,x.d3,x.d5,l);assert.equal(v.valid,false);});
